# Lab: Packet Tracing Network Communication Using Cisco Packet Tracer

## Overview
This lab demonstrates how data traverses a network by simulating client-server communication using Cisco Packet Tracer. The lab will showcase the journey of an HTTP packet from a client device to a web server while detailing the encapsulation and de-encapsulation process through the OSI model's layers.

## Objective
- To analyze data transmission through a network using the OSI model.
- To understand how encapsulation and de-encapsulation occur at each layer.
- To use Cisco Packet Tracer's simulation mode to visually track a packet's journey.

## Prerequisites
- Basic knowledge of the OSI and TCP/IP models.
- Cisco Packet Tracer installed.
- A basic network topology set up in Packet Tracer (Client PC, Switch, Router, and Web Server).
- Packet Tracer simulation file for reference (download from lab repository if available).

## Lab Setup
1. **Devices**:
   - PC1 (Client)
   - Switch0 (Network Switch)
   - Router0 (Gateway Router)
   - Server0 (Web Server)
2. **Connections**:
   - Connect PC1 to Switch0 using a copper straight-through cable.
   - Connect Switch0 to Router0.
   - Connect Router0 to Server0.

## Lab Steps

### 1. Build the Network Topology in Packet Tracer
   - Open Cisco Packet Tracer.
   - Add the following devices to your workspace:
     - PC1 (End Device)
     - Switch0 (Switch)
     - Router0 (Router)
     - Server0 (Server)
   - Connect each device using appropriate cables.

### 2. Configure IP Addresses
   - **PC1 Configuration**:
     - IP Address: `192.168.10.10`
     - Subnet Mask: `255.255.255.0`
     - Default Gateway: `192.168.10.1`
   - **Router0 Configuration**:
     - FastEthernet0/0: `192.168.10.1` (Connected to Switch0)
     - FastEthernet0/1: `192.168.20.1` (Connected to Server0)
   - **Server0 Configuration**:
     - IP Address: `192.168.20.10`
     - Subnet Mask: `255.255.255.0`
     - Default Gateway: `192.168.20.1`

### 3. Configure the Web Server
   - Click on Server0, go to the `Services` tab, and enable the HTTP service.
   - Verify that the HTTP server is running.

### 4. Access the Web Server from PC1
   - Go to `Simulation Mode` in Packet Tracer.
   - Click on PC1, navigate to `Desktop` > `Web Browser`.
   - Enter the URL: `http://192.168.20.10`.
   - Click `Go` and observe the packet flow in simulation mode.

### 5. Analyze the Packet Flow
   - As the packet travels through the network, take note of the following OSI layers:
     - **Layer 7 - Application Layer**: The HTTP request is generated by the web browser.
     - **Layer 4 - Transport Layer**: TCP is used to ensure reliable transmission.
     - **Layer 3 - Network Layer**: The packet is encapsulated with IP addresses for routing.
     - **Layer 2 - Data Link Layer**: MAC addresses are added for the switch to forward the frame.
     - **Layer 1 - Physical Layer**: The frame is transmitted as electrical signals over the cable.

### 6. Packet Encapsulation and De-encapsulation
   - As the packet reaches each network device (Switch, Router), observe how it is processed:
     - **Switch**: Uses MAC addresses to determine the destination port.
     - **Router**: De-encapsulates Layer 2 headers and uses Layer 3 information (IP addresses) to forward the packet.
     - **Server**: De-encapsulates all layers until the application layer data is extracted.

## Results and Observations
- Successful HTTP communication was established between PC1 and the Web Server.
- The simulation mode effectively displayed the encapsulation and de-encapsulation process at each OSI layer.

## Recommendations
- For a more in-depth analysis, enable additional protocols such as DNS and ARP in the Packet Tracer filter settings.
- Experiment with different transport layer protocols (e.g., UDP) to see their impact on packet delivery.

## Conclusion
This lab provided a detailed visualization of packet traversal through a network using Cisco Packet Tracer. Understanding how packets are encapsulated and processed at each OSI layer is crucial for effective network troubleshooting and design.
